[build]
  publish = "docs/dist/"
  command = "yarn install && cd packages/wilson && yarn && yarn build && cd ../../docs && yarn && yarn build"

[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.22.10"