[build]
  base = "docs/"
  publish = "dist/"
  command = "yarn add wilson@latest && yarn run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "14", NETLIFY_USE_YARN = "true", YARN_VERSION="1.22.10" }